### PR TITLE
103 signup login keyboard glitch

### LINKED ISSUE #103: signup and login keyboard view glitches [bugfix]
current the keyboardAvoidingView and error text is a little wonky. might be due to merge conflicts or sum idk

- [x] make sure error text popups are good, make sure the spacing is also good (they shouldn't take up spacing when they're not there unless specified in the design
- [x] make sure the views don't jump when typing in username etc
- [x] on signup page, keyboard avoiding view makes it so that you can't see the top fields when typing them in 
- [x] Terms and conditions checkbox didn’t appear → incorrect format, covered by “sign up” button
- [x] Increase distance between “sign up” button and username input box (12 px)
- [x] change 'username' field in login to 'email' field (we don't support it username login rn)
- [x] “Remember me” and “forgot password” are misaligned → should be lined up with the edges of the input boxes + button

### PR DESCRIPTION
**Pull request by owennjpr**
# Description

Fixed a number of styling issues on the login and signup page including: fixed forgot password and remember me spacing, made sure the correct errors displayed when trying to log in, fixing cut off "terms of use" line, fixed and added scrolling capabilities to the keyboard avoiding view when entering things into the text input fields. Fixed the glitchy effect when switching between text inputs in the keyboard view

## Issues
Resolve #103 

## Test

- open the app and log out if automatically logged in
- tap login, the page should match the figma
- type in a bad email, should get email error
- type in a good email and a bad password and should get the password error
- while typing in these fields you should have no issues with the keyboard avoiding view covering up anything
- go back and tap sign up, the page should match the figma (specifically should see the bottom line of the terms and conditions statement)
- when tapping on one of the top fields the keyboard should appear without moving the ui elements
- tap on elements lower down like username and password both while the keyboard is already active and when it is not active
- try scrolling through the inputs while the keyboard is open

## Possible Downsides

to get the proper email/password errors to display I had to override the existing error display system a bit, so it is possible that the incorrect password error may display in cases where something else went wrong during the login (though I think previously it would have just shown the email error in that case anyway). Had very minor ui scrolling issues on the login page but have not been able to replicate them in recent testing despite not having intentionally fixed anything.

## Additional Documentations

added a new npm package: https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view

### CODE REVIEW

**Review by johnny-t06 — COMMENTED** [review]
The scrollview definetly feels a lot better for login and signup, and errors are cleaner. 
I do have a two requests. My screen jitters to the right when the password error pops up.

https://github.com/user-attachments/assets/15a256da-2980-4dd9-b489-265b9e89fc67
Could you also make an error when a user signs up with a duplicate email?

**Comment by LordofMankid** [comment]
login feels really clean, but there's a SLIGHT issue where if i tap on a textInput and the screen moves, it drifts super slightly before stopping. if it's a hard fix (> 30 minutes) don't worry about it lol

**Comment by owennjpr** [comment]
@johnny-t06 both of your requests should be fixed

@LordofMankid I added the required and unique field for the username in the userModel.ts file and attempted a fix for the scroll drifting issue. It has something to do with the animation in of the keyboard, so I allowed it to have more of a delay, which fixes the drift but delays the whole scroll animation. I'll leave it up to your choice if you would rather have the drift or the delay (since it seems like its a characteristic built in to the package) and feel free to revert "keyboard opening time adjustment" if you want to go back to the drifting version

**Comment by owennjpr** [comment]
Removed the remember me button

**Review by LordofMankid — APPROVED** [review]
perf let's get this MERGED

**Pull request merged**
