### PR TITLE
114 route to user profiles on posts

### PR DESCRIPTION
**Pull request by sristii**
the styling for the user card when enlarging the post is still off - I tried to fix it but its not workinggggggg

ill prob look at it again later

WIP DONUT REVIEW YET

### CODE REVIEW

**Comment by sristii** [comment]
ok when clicking the little user tab on posts that shows who posted it - it shud take u to their profile (also when expanding it)

**Review by LordofMankid — APPROVED** [review]
LGTM

**Review by LordofMankid — COMMENTED** [review]
LGTM (for now) (again). some notes for history; we had to jury rig a new auth flow to re-authenticate before deleting because firebase stuff. it's kind of janky how its set up and the designers might wanna redo this flow. also not sure if we're using deleteOptionsModal correctly i think we have an in-house modal component for this and we pass the rest in as children? not sure tbh lmao

**Review by johnny-t06 — APPROVED** [review]
LGTM, hopefully the refs can hold the requests down. User profile looks good. 
Note: It might be possble to refactor the DeleteOptionsModal with the OptionsModel, I took inspiration as they were similar but had different stage two modals.

**Pull request merged**
